name: repro-kit-ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: bash benchmarks/run_all.sh --mode sandbox --repetitions 5
      - run: python3 scripts/analyze_results.py --input results --out plots
      - run: ls -l plots tables
